### ISSUE TITLE
Angular 8.x 버젼에서도 동일하게 사용할 수 있나요?

### ISSUE THREAD

**Issue by ninezero90hy** [paige0701/angular-view-containerRef#1]
@paige0701 궁금해서요 :) 답변 좀 부탁드립니다.

**Comment by paigechoi** [comment]
![image](https://user-images.githubusercontent.com/42233517/58696932-91dc9000-83d3-11e9-8e93-3814cf5a095f.png)
네 가능합니다 ^^

**Comment by ninezero90hy** [comment]
@paigechoi 답변 감사합니다

**Comment by ninezero90hy** [comment]
@paigechoi 동적 로딩하려고 하는 컴포넌트가 application context에 없어도 생성할 수 있는 방법도 있을까요?
